### ISSUE TITLE
Error Message : "Only the owner can confirm the withdrawal"

### ISSUE THREAD

**Issue by ashrhmn** [maticnetwork/wallet-widget-example#5]
![image](https://user-images.githubusercontent.com/43120823/153916256-a57c72e5-b5bc-4ce6-9dfc-c1456edb82e1.png)

Every time I transfer from Matic to Georli Network, I am given an error message like this. I am using only one account, so I only should be the owner here. But I can not withdraw because of this issue.

**Comment by ujjwalgupta94** [comment]
@ashrhmn try now, issue should be fixed. Let me know if it is not.

**Comment by ashrhmn** [comment]
> @ashrhmn try now, issue should be fixed. Let me know if it is not.

Turned out to be I was using the exact template cloned from the example repository and no `app name` was used in the widget config. Then I registered an widget from the widget builder and used the name value from newly created widget and it worked as it should be.
